### PR TITLE
Add a Quick Search provider for GoQL

### PR DESCRIPTION
**Pull request by jschmidt42**
goql

### CODE REVIEW

**Comment by SugoiDev** [comment]
Just did a quick test and it works!

One question: is it supposed to be case-sensitive by default?
It seems to be

screenshot 2020 02 05-01 21 39

image

**Comment by SugoiDev** [comment]
Tested a bit more and got an exception:

```
ArgumentException: An item with the same key has already been added. Key: ...
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <437ba245d8404784b9fbab9b439ac908>:0)
Unity.GoQL.GoQLExecutor.FindType (System.String name) (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:67)
Unity.GoQL.GoQLExecutor.PerformTypeDiscrimination (System.String value) (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:322)
Unity.GoQL.GoQLExecutor.PerformDiscrimination (Unity.GoQL.Discrimator discriminator) (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:272)
Unity.GoQL.GoQLExecutor.FilterByDiscriminators () (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:260)
Unity.GoQL.GoQLExecutor.ExecuteCode (Unity.GoQL.GoQLCode i) (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:130)
Unity.GoQL.GoQLExecutor.Execute () (at Library/PackageCache/com.unity.goql@4e5cff55d9/Runtime/GoQLExecutor.cs:110)
Unity.GoQL.GoQLSearchProvider+<SearchItems>d__5.MoveNext () (at Library/PackageCache/com.unity.goql@4e5cff55d9/Editor/GoQLSearchProvider.cs:87)
Unity.QuickSearch.AsyncSearchSession.NextItem (Unity.QuickSearch.SearchItem& nextItem) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/AsyncSearchSession.cs:180)
Unity.QuickSearch.AsyncSearchSession.FetchSome (System.Collections.Generic.List`1[T] items, System.Int64 maxFetchTimeMs) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/AsyncSearchSession.cs:159)
Unity.QuickSearch.SearchService.GetItems (Unity.QuickSearch.SearchContext context, Unity.QuickSearch.SearchFilter filter) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/SearchService.cs:438)
Rethrow as Exception: Failed to get fetch GoQL provider items.
UnityEngine.DebugLogHandler:LogException(Exception, Object)
List<SearchItem> Unity.QuickSearch.SearchService.GetItems(SearchContext context, SearchFilter filter) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/SearchService.cs:445)
List<SearchItem> Unity.QuickSearch.SearchService.GetItems(SearchContext context) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/SearchService.cs:236)
void Unity.QuickSearch.QuickSearch.Refresh() (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/QuickSearch.cs:893)
void Unity.QuickSearch.QuickSearch.DebouncedRefresh() (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/QuickSearch.cs:1443)
Rect Unity.QuickSearch.QuickSearch.DrawToolbar(SearchContext context) (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/QuickSearch.cs:1426)
void Unity.QuickSearch.QuickSearch.OnGUI() (at Library/PackageCache/com.unity.quicksearch@1.5.2-preview.1/Editor/QuickSearch.cs:809)
void UnityEditor.HostView.Invoke(string methodName, object obj)
void UnityEditor.HostView.Invoke(string methodName)
void UnityEditor.HostView.OldOnGUI()
```

With caches, whenever possible, I usually use `myCache[key] = value` instead of `myCache.Add(key, value)`.

**Comment by jschmidt42** [comment]
> One question: is it supposed to be case-sensitive by default?

I think GoQL is case-sensitive by default. @smnwttbr can confirm.

**Comment by jschmidt42** [comment]
> With caches, whenever possible, I usually use `myCache[key] = value` instead of `myCache.Add(key, value)`.

I think this issue can be fixed in GoQL directly (CC @smnwttbr) regardless of the Quick Search integration.

**Comment by smnwttbr** [comment]
> > One question: is it supposed to be case-sensitive by default?
> 
> I think GoQL is case-sensitive by default. @smnwttbr can confirm.

Currently yes, however this might change.

**Pull request merged**
